version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Node.js version: 14, 12, 10
        VARIANT: 14
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: showdown
      MYSQL_USER: showdown
      MYSQL_PASSWORD: showdown

  play:
    build:
      context: .
      dockerfile: Dockerfile-web
    restart: unless-stopped
    ports:
      - 8443:443
    volumes:
      - ../:/var/www/html
      - ./certs/localhost.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem
      - ./certs/localhost-key.pem:/etc/ssl/private/ssl-cert-snakeoil.key

  website:
    build:
      context: .
      dockerfile: Dockerfile-web
    restart: unless-stopped
    ports:
      - 8444:443
    volumes:
      - ../website:/var/www/html
      - ./certs/localhost.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem
      - ./certs/localhost-key.pem:/etc/ssl/private/ssl-cert-snakeoil.key

volumes:
  db_data: