FROM php:apache

# MySQL PDO Driver
RUN docker-php-ext-install pdo pdo_mysql

# Apache mods
RUN a2enmod authz_groupfile
RUN a2enmod headers

# xdebug
RUN pecl install xdebug-3.0.1 \
    && docker-php-ext-enable xdebug
COPY xdebug.ini $PHP_INI_DIR/conf.d